// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVWV2RTzBh5LgGASEJ1x7vQvhh4MjPzG8',
    appId: '1:630359897407:web:17fd9d8243fd9824b68f8a',
    messagingSenderId: '630359897407',
    projectId: 'pawpaw-project-5f9c7',
    authDomain: 'pawpaw-project-5f9c7.firebaseapp.com',
    storageBucket: 'pawpaw-project-5f9c7.firebasestorage.app',
    measurementId: 'G-ZM4QL3JD81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Sw0WiDdMfKK0RK8FhGL6SUOod9bsmro',
    appId: '1:630359897407:android:14ef892c0c41e931b68f8a',
    messagingSenderId: '630359897407',
    projectId: 'pawpaw-project-5f9c7',
    storageBucket: 'pawpaw-project-5f9c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpTTgCCoe11ib6ufBVADUm7U01JYocBNM',
    appId: '1:630359897407:ios:9e4d46f5c3276158b68f8a',
    messagingSenderId: '630359897407',
    projectId: 'pawpaw-project-5f9c7',
    storageBucket: 'pawpaw-project-5f9c7.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpTTgCCoe11ib6ufBVADUm7U01JYocBNM',
    appId: '1:630359897407:ios:9e4d46f5c3276158b68f8a',
    messagingSenderId: '630359897407',
    projectId: 'pawpaw-project-5f9c7',
    storageBucket: 'pawpaw-project-5f9c7.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVWV2RTzBh5LgGASEJ1x7vQvhh4MjPzG8',
    appId: '1:630359897407:web:f6f5e658e452d80ab68f8a',
    messagingSenderId: '630359897407',
    projectId: 'pawpaw-project-5f9c7',
    authDomain: 'pawpaw-project-5f9c7.firebaseapp.com',
    storageBucket: 'pawpaw-project-5f9c7.firebasestorage.app',
    measurementId: 'G-7EX8577FND',
  );

}